# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeMyStyle - Website Design and Development Services
email: qwertsy2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creative and professional website design and development.
  Your vision, your passion, your style, your dream. Our quality code. It's a beautiful match.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codemystyle.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
